_extends: repo-settings:.github/settings.yml

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      enforce_admins: true
      required_status_checks:
        strict: true
        contexts:
          - "call-terraform-ci-pipeline / CI Pipeline"
          - "call-terraform-ci-pipeline / Infrastructure Test"
      # Restrict who can merge to this branch
      restrictions:
        apps: []
        users: []
        teams: [github-mergers]
